version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gps_tracking_db
    ports:
      - "5432:5432"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
